# Generated by Django 2.1 on 2019-10-03 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painter', '0003_auto_20191003_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('code', models.CharField(max_length=20, verbose_name='验证码')),
                ('email', models.EmailField(max_length=256, verbose_name='邮箱')),
                ('send_type', models.IntegerField()),
                ('send_time', models.DateTimeField(default=datetime.datetime(2019, 10, 3, 17, 27, 46, 934915), verbose_name='发送时间')),
            ],
        ),
    ]
